--- 
- name: create openssl key rsa 2048 bits 
  community.crypto.openssl_privatekey: 
    path: /etc/pki/tls/private/httpd.pem 
    size: 2048 

- name: create self signed openssl certificate 
  community.crypto.x509_certificate: 
    path: /etc/pki/tls/certs/httpd.crt 
    privatekey_path: /etc/pki/tls/private/httpd.pem 
    provider: selfsigned 

- name: Enable https protocol, add certificate 
  replace: 
    path: /etc/httpd/conf.d/ssl.conf 
    regexp: '#SSLCertificateFile /etc/pki/tls/certs/localhost.crt' 
    replace: 'SSLCertificateFile /etc/pki/tls/certs/httpd.crt' 

- name: Enable https protocol, add private key 
  replace: 
    path: /etc/httpd/conf.d/ssl.conf 
    regexp: '#SSLCertificateKeyFile /etc/pki/tls/private/localhost.key' 
    replace: ' SSLCertificateKeyFile /etc/pki/tls/private/httpd.key' 
  notify: 
  - Restart apache 