--- 
- name: Install apache 
  ansible.builtin.yum: 
    name: httpd 
    state: present 

- name: Install mod_ssl 
  ansible.builtin.yum: 
    name: mod_ssl 
    state: present 

- name: Start apache 
  ansible.builtin.service: 
    name: httpd 
    state: started 